### ISSUE TITLE
Use showdown for offscreen rendering?

### ISSUE THREAD

**Issue by SuperIceCN** [McShare/xenforo-markdown#1]
`showdown` is another markdown lib writen in JavaScript. It offers the capacity for offscreen rendering, that means, we can transfer the rendered html directly instead of the markdown content. I believe this advance will provide users with better experience.  Also, it's more friendly to search engines such as bing, baidu and google.
What's more, if we don't use offscreen rendering as the final solution,  showdown still works faster than markdown-it when there's many Chinese characters, or HanZi , in the markdown code. Showdown also offers the ability to control the grammar of markdown and I have already changed my wiki project from markdown-it to showdown.
Could you please consider my suggestion? Thanks a lot!

**Comment by Subilan** [comment]
Thanks for your brilliant advice! It seemed that Showdown is MUCH better than markdown-it and is able to solve the crucial problem I am currently facing according to your introduction. I will try implementing it today ;)

**Comment by Subilan** [comment]
Replaced markdown-it with Showdown now.

**Comment by Subilan** [comment]
Turns out a bad idea. Showdown is poorly maintained since 2022, and there are unresolved issues like https://github.com/showdownjs/showdown/issues/870.
