### ISSUE TITLE
这个会和部分BB内嵌代码冲突

### ISSUE THREAD

**Issue by jiangnai901** [McShare/xenforo-markdown#4]
我今天发现这个Xenforo的Markdown会与其内嵌的BB代码发生冲突，使其内嵌BB代码内容不能正常显示
[https://www.cnxfans.com/threads/showdown-xenforo-markdown.1631/](url)
代码教程采自该处，希望解决一下

**Comment by Subilan** [comment]
我猜测你可能下载到了旧版本，因为在minebbs上使用的时候也遇到了类似的问题，后来经过修改解决了。

Release里的v1.0.0并不是最新版，经过我的检查，这个版本是不支持iframe的。建议你从action里下载最新版本试试。

附：这篇回复发布时最新版本action页面：
https://github.com/McShare/xenforo-markdown/actions/runs/2149454296

**Comment by Subilan** [comment]
![E0A85B7B-AEF8-418B-8185-04C31DB329F1](https://user-images.githubusercontent.com/36447840/173095203-2d187b0c-49c4-458b-bd4d-c15bbaf75d51.png)

另外在这张图片里，被过滤掉的iframe下面还有一行script，目测是用来自适应的。目前为了安全性问题并没有支持script，所以最新版使用后虽然iframe会显示正常但还是会显示出这行script。

大概下个星期我会着手解决script这个问题。

**Comment by Subilan** [comment]
fixed in https://github.com/McShare/xenforo-markdown/commit/45ecec340250bcd2f66210489b9aebedcde8f4eb
